name: Continuous Integration with GitHub Actions
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar y ubicarse en la rama main
      uses: actions/checkout@v2
      - name: Instalar dependencias
      uses: npm install
      - name: Ejecutar test
      uses: npm test
